apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-nodeplugin-fluid
  namespace: fluid-system
spec:
  template:
    spec:
      containers:
        # change the following two images if necessary
        - name: node-driver-registrar
          image: mirrors.tencent.com/alluxio/alluxiotest/fluid/csi-node-driver-registrar:v1.2.0
        - name: plugins
          image: mirrors.tencent.com/alluxio/alluxiotest/fluid/fluid-csi:0.1
