#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#
{{ if .Values.zone -}}

{{- $shortCircuitEnabled := .Values.shortCircuit.enabled }}
{{- $needDomainSocketVolume := and $shortCircuitEnabled (eq .Values.shortCircuit.policy "uuid") }}
{{- $hostNetwork := .Values.worker.hostNetwork }}
{{- $hostPID := .Values.worker.hostPID }}
{{- $name := include "alluxio.name" . }}
{{- $fullName := include "alluxio.fullname" . }}
{{- $chart := include "alluxio.chart" . }}
{{- $release := .Release }}
{{- $valuesInner := .Values }}
{{- $alluxioWorkerResources := include "alluxio.worker.resources" . }}
{{- $alluxioWorkerTieredstoreVolumeMounts := include "alluxio.worker.tieredstoreVolumeMounts" . }}
{{- $alluxioJobWorkerResources := include "alluxio.jobWorker.resources" . }}
{{- $alluxioWorkerTieredstoreVolumes := include "alluxio.worker.tieredstoreVolumes" . }}
{{- range $key, $value := $.Values.zone}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}-{{ $key }}
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $release.Name }}
    heritage: {{ $release.Service }}
    role: alluxio-worker
    fluid.io/dataset: {{ $release.Namespace }}-{{ $release.Name }}
    node.info.kubernetes.io/zone: {{ $key }}
    fluid.io/dataset-placement: {{ $valuesInner.placement }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ $release.Name }}
      role: alluxio-worker
  serviceName: {{ $fullName }}-{{ $key }}
  replicas: {{ $value }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        chart: {{ $chart }}
        release: {{ $release.Name }}
        heritage: {{ $release.Service }}
        role: alluxio-worker
        fluid.io/dataset: {{ $release.Namespace }}-{{ $release.Name }}
        fluid.io/dataset-placement: {{ $valuesInner.placement }}
    spec:
      serviceAccountName: node-info
      enableServiceLinks: false
      hostNetwork: {{ $hostNetwork }}
      hostPID: {{ $valuesInner.worker.hostPID }}
      dnsPolicy: {{ $valuesInner.worker.dnsPolicy | default ($hostNetwork | ternary "ClusterFirstWithHostNet" "ClusterFirst") }}
      securityContext:
        fsGroup: {{ $valuesInner.fsGroup }}
      nodeSelector:
        node.info.kubernetes.io/zone: {{ $key }}
      {{- if $valuesInner.worker.nodeSelector }}
{{ toYaml $valuesInner.worker.nodeSelector | trim | indent 8  }}
      {{- else if $valuesInner.nodeSelector }}
{{ toYaml $valuesInner.nodeSelector | trim | indent 8  }}
      {{- end }}
      {{- if $valuesInner.tolerations }}
      tolerations:
{{ toYaml $valuesInner.tolerations | indent 8 }}
      {{- end }}
      initContainers:
        - name: init
          image: mirrors.tencent.com/alluxio/alluxiotest/fluid/node-info:0.2
          imagePullPolicy: Always
          env:
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OUTPUT_DIR
              value: /output
          volumeMounts:
            - name: node-data
              mountPath: /output
        {{ if $valuesInner.initUsers.enabled -}}
        - name: init-users
          image: {{ $valuesInner.initUsers.image }}:{{ $valuesInner.initUsers.imageTag }}
          imagePullPolicy: {{ $valuesInner.initUsers.imagePullPolicy }}
          command: ["/entrypoint.sh"]
          args:
            - "init_users"
            - "chmod_tierpath"
          env:
          {{- if $valuesInner.initUsers.envUsers }}
            - name: FLUID_INIT_USERS
              value: {{$valuesInner.initUsers.envUsers | quote }}
          {{- end }}
          {{- if $valuesInner.initUsers.envTieredPaths }}
            - name: FLUID_TIERSTORE_PATHS
              value: {{ $valuesInner.initUsers.envTieredPaths | quote }}
          {{- end }}
          volumeMounts:
            - name: dir
              mountPath: /tmp
            - name: user
              mountPath: /tmp/passwd
            - name: group
              mountPath: /tmp/group
            {{- if $valuesInner.tieredstore -}}
{{- $alluxioWorkerTieredstoreVolumeMounts }}
            {{- end -}}
        {{- end }}
      containers:
        - name: alluxio-worker
          image: {{ $valuesInner.image }}:{{ $valuesInner.imageTag }}
          imagePullPolicy: {{ $valuesInner.imagePullPolicy }}
          securityContext:
            runAsUser: {{ $valuesInner.user }}
            runAsGroup: {{ $valuesInner.group }}
          {{- if $valuesInner.worker.resources  }}
{{ $alluxioWorkerResources | indent 10 }}
          {{- end }}
          command: ["/entrypoint.sh"]
          {{- if $valuesInner.worker.args }}
          args:
{{ toYaml $valuesInner.worker.args | trim | indent 12 }}
          {{- end }}
          env:
          - name: ALLUXIO_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          {{- if not $valuesInner.worker.hostNetwork }}
          - name: ALLUXIO_WORKER_CONTAINER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- end }}
          {{- range $key, $value := $valuesInner.worker.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ $fullName }}-config
          ports:
          - containerPort: {{ $valuesInner.worker.ports.rpc }}
            name: rpc
          - containerPort: {{ $valuesInner.worker.ports.web }}
            name: web
          volumeMounts:
            - name: node-data
              mountPath: /location
            {{ if $valuesInner.hadoopConfig  -}}
            {{ if or $valuesInner.hadoopConfig.includeCoreSite $valuesInner.hadoopConfig.includeHdfsSite -}}
            - name: hdfs-confs
              mountPath: /hdfs-config
              readOnly: true
            {{- end }}
            {{- end }}
            {{- if $valuesInner.initUsers.enabled }}
            - name: user
              mountPath: /etc/passwd
              readOnly: true
            - name: group
              mountPath: /etc/group
              readOnly: true
            {{- end}}
            {{- if $needDomainSocketVolume }}
            - name: alluxio-domain
              mountPath: /opt/domain
            {{- end }}
            {{- if $valuesInner.ufsPaths }}   
              {{- range $valuesInner.ufsPaths }}
            - mountPath: {{ .containerPath }}
              name: {{ .name }}
              {{- end }}
            {{- end }}
            {{- if $valuesInner.ufsVolumes }}   
              {{- range $valuesInner.ufsVolumes }}
            - mountPath: {{ .containerPath }}
              name: {{ .name }}
              {{- end }}
            {{- end }}
            {{- if $valuesInner.secrets -}}
              {{- if $valuesInner.secrets.worker -}}
{{- include "alluxio.worker.secretVolumeMounts" . }}
              {{- end -}}
            {{- end -}}
            {{- if $valuesInner.tieredstore -}}
{{- $alluxioWorkerTieredstoreVolumeMounts }}
            {{- end -}}
            {{- if $valuesInner.mounts -}}
{{- include "alluxio.worker.otherVolumeMounts" . }}
            {{- end }}
        - name: alluxio-job-worker
          image: {{ $valuesInner.image }}:{{ $valuesInner.imageTag }}
          securityContext:
            runAsUser: {{ $valuesInner.user }}
            runAsGroup: {{ $valuesInner.group }}
          imagePullPolicy: {{ $valuesInner.imagePullPolicy }}
          {{- if $valuesInner.jobWorker.resources  }}
{{ $alluxioJobWorkerResources | indent 10 }}
          {{- end }}
          command: ["/entrypoint.sh"]
          {{- if $valuesInner.jobWorker.args }}
          args:
{{ toYaml $valuesInner.jobWorker.args | trim | indent 12 }}
          {{- end }}
          env:
          - name: ALLUXIO_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          {{- if not $valuesInner.worker.hostNetwork }}
          - name: ALLUXIO_WORKER_CONTAINER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- end }}
          {{- range $key, $value := $valuesInner.jobWorker.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ $fullName }}-config
          ports:
          - containerPort: {{ $valuesInner.jobWorker.ports.rpc }}
            name: job-rpc
          - containerPort: {{ $valuesInner.jobWorker.ports.data }}
            name: job-data
          - containerPort: {{ $valuesInner.jobWorker.ports.web }}
            name: job-web
          volumeMounts:
            - name: node-data
              mountPath: /location
            {{ if $valuesInner.hadoopConfig -}}
            {{ if or $valuesInner.hadoopConfig.includeCoreSite $valuesInner.hadoopConfig.includeHdfsSite -}}
            - name: hdfs-confs
              mountPath: /hdfs-config
              readOnly: true
            {{- end }}
            {{- end }}
            {{- if $valuesInner.initUsers.enabled }}
            - name: user
              mountPath: /etc/passwd
              readOnly: true
            - name: group
              mountPath: /etc/group
              readOnly: true
            {{- end}}
            {{- if $needDomainSocketVolume }}
            - name: alluxio-domain
              mountPath: /opt/domain
            {{- end }}
            {{- if $valuesInner.ufsPaths }}   
              {{- range $valuesInner.ufsPaths }}
            - mountPath: {{ .containerPath }}
              name: {{ .name }}
              {{- end }}
            {{- end }}
            {{- if $valuesInner.ufsVolumes }}   
              {{- range $valuesInner.ufsVolumes }}
            - mountPath: {{ .containerPath }}
              name: {{ .name }}
              {{- end }}
            {{- end }}
            {{- if $valuesInner.secrets }}
              {{- if $valuesInner.secrets.worker }}
{{- include "alluxio.worker.secretVolumeMounts" . }}
              {{- end -}}
            {{- end }}
            {{- if $valuesInner.tieredstore }}
{{- $alluxioWorkerTieredstoreVolumeMounts }}
            {{- end }}
            {{- if $valuesInner.mounts }}
{{- include "alluxio.worker.otherVolumeMounts" . }}
            {{- end }}
      restartPolicy: Always
      volumes:
        - name: node-data
          emptyDir: { }
        {{ if $valuesInner.hadoopConfig -}}
        {{ if or $valuesInner.hadoopConfig.includeCoreSite $valuesInner.hadoopConfig.includeHdfsSite -}}
        - name: hdfs-confs
          configMap:
            name: {{ $valuesInner.hadoopConfig.configMap }}
            items:
            {{ if $valuesInner.hadoopConfig.includeHdfsSite -}}
            - key: hdfs-site.xml
              path: hdfs-site.xml
            {{- end }}
            {{- if $valuesInner.hadoopConfig.includeCoreSite }}
            - key: core-site.xml
              path: core-site.xml
            {{- end }}
        {{- end }}
        {{- end }}
        {{- if $valuesInner.initUsers.enabled }}
        - name: dir
          hostPath:
            path: {{ $valuesInner.initUsers.dir }}
            type: DirectoryOrCreate 
        - name: user         
          hostPath:
            path: {{ $valuesInner.initUsers.dir }}/passwd
            type: FileOrCreate
        - name: group         
          hostPath:
            path: {{ $valuesInner.initUsers.dir }}/group
            type: FileOrCreate
        {{- end }}
        {{- if $needDomainSocketVolume }}
{{- include "alluxio.worker.shortCircuit.volume" . }}
        {{- end }}
        {{- if $valuesInner.secrets }}
          {{- if $valuesInner.secrets.worker }}
{{- include "alluxio.worker.secretVolumes" . }}
          {{- end }}
        {{- end }}
        {{- if $valuesInner.tieredstore }} 
{{- $alluxioWorkerTieredstoreVolumes }}
        {{- end}}
        {{- if $valuesInner.mounts }}   
          {{- range $valuesInner.mounts }}
        - name: "{{ .name }}"
          persistentVolumeClaim:
            claimName: "{{ .name }}"
          {{- end }}
        {{- end }}
        {{- if $valuesInner.ufsPaths }}   
          {{- range $valuesInner.ufsPaths }}
        - hostPath:
            path: {{ .hostPath }}
            type: ""
          name: {{ .name }}
          {{- end }}
        {{- end }}
        {{- if $valuesInner.ufsVolumes }}   
          {{- range $valuesInner.ufsVolumes }}
        - name: "{{ .name }}"
          persistentVolumeClaim:
            claimName: "{{ .name }}"
          {{- end }}
        {{- end }}
---
{{- end }}
{{- end }}