apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataset-controller
  namespace: fluid-system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: mirrors.tencent.com/alluxio/alluxiotest/fluid/dataset-controller:0.1
          env:
            - name: ALLUXIO_DATALOAD_IMAGE_ENV
              value: mirrors.tencent.com/alluxio/alluxiotest/venus/alluxio:v0.1
