apiVersion: apps/v1
kind: Deployment
metadata:
  name: alluxioruntime-controller
  namespace: fluid-system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: mirrors.tencent.com/alluxio/alluxiotest/fluid/alluxioruntime-controller:0.1
          env:
            - name: ALLUXIO_INIT_IMAGE_ENV
              value: mirrors.tencent.com/alluxio/alluxiotest/fluid/init-users:0.1
            - name: ALLUXIO_RUNTIME_IMAGE_ENV
              value: mirrors.tencent.com/alluxio/alluxiotest/venus/alluxio:v0.1
            - name: ALLUXIO_FUSE_IMAGE_ENV
              value: mirrors.tencent.com/alluxio/alluxiotest/venus/alluxio:v0.1

