apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataset-controller
  namespace: fluid-system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: mirrors.tencent.com/alluxio/alluxiotest/fluid/dataset-controller:0.1
          env:
            - name: ALLUXIO_DATALOAD_IMAGE_ENV
              value: alluxio/alluxio:2.6.2-tq-1.3.1-konajdk11
