apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: fuse.csi.fluid.io
spec:
  attachRequired: false
  podInfoOnMount: true

apiVersion: {{ ternary "storage.k8s.io/v1" "storage.k8s.io/v1beta1" (semverCompare ">=1.18.0-0" .Capabilities.KubeVersion.Version) }}
kind: CSIDriver
metadata:
  name: fuse.csi.fluid.io
spec:
  attachRequired: false
  podInfoOnMount: true